# Generated by Django 2.2.5 on 2019-09-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
